apiVersion: v1
kind: Service
metadata:
  name: task-board-service
spec:
    type: NodePort
    ports: 
      - targetPort: 3001
        port: 80
        nodePort: 30008
    selector:
        app: task-board-api
        type: back-end